### ISSUE TITLE
TypeError: argument of type 'WindowsPath' is not iterable

### ISSUE THREAD

**Issue by Pomax** [florensie/ue-wwise-extractor#1]
Trying to run this on the Yoku's Island data dir, and I get the following error:
```
> python extract.py "f:\Steam\steamapps\common\Yokus Island Express\data\sounds\windows"
Non SoundBankInfo json file skipped: f:\Steam\steamapps\common\Yokus Island Express\data\sounds\windows\PluginInfo.json
Bank: backgrounds
==================================================
Traceback (most recent call last):
  File "extract.py", line 131, in <module>
    main(sys.argv[1:])
  File "extract.py", line 103, in main
    subprocess.run([BANK_EXTR_EXE, wwise_path / soundbank['Path']])  # Extract soundbank to cwd
  File "C:\Program Files\Python37\lib\subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Program Files\Python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\Python37\lib\subprocess.py", line 1148, in _execute_child
    args = list2cmdline(args)
  File "C:\Program Files\Python37\lib\subprocess.py", line 555, in list2cmdline
    needquote = (" " in arg) or ("\t" in arg) or not arg
TypeError: argument of type 'WindowsPath' is not iterable
```

**Comment by florensie** [comment]
I think I fixed it, let me know if it doesn't work.

**Comment by Pomax** [comment]
Doesn't look like it does, but some searching hints that the problem might be using `/` concatenation rather than `os.path.join` (see https://stackoverflow.com/a/63989346/740553)

**Comment by Pomax** [comment]
Did some testing and this gets it closer, but then runs into problems when recursing (I think?)
```python
import sys
from pathlib import Path
import json
import subprocess
import os
import shutil

assert sys.version_info >= (3, 6)

# File paths
MODULE_PATH = Path(__file__).parent.absolute()
TMP_PATH = Path(os.path.join(MODULE_PATH, 'tmp'))
OUT_PATH = Path(os.path.join(MODULE_PATH, 'out'))
VGMSTREAM_EXE = Path(os.path.join(MODULE_PATH, 'test', 'test.exe'))
BANK_EXTR_EXE = str(os.path.join(MODULE_PATH, 'bnkextr.exe'))

DIV_LENGTH = 50


def create_dir(path):
    """Helper method to create a directory if it doesn't exist yet"""
    try:
        path.mkdir(parents=True, exist_ok=True)
    except FileExistsError:
        print(f'Cannot create directory ({path}) because file with same name exists')
        sys.exit(1)


def cleanup():
    """Cleanup the out and tmp directories"""
    if TMP_PATH.exists():
        shutil.rmtree(TMP_PATH)
    if OUT_PATH.exists():
        shutil.rmtree(OUT_PATH)

    create_dir(TMP_PATH)
    create_dir(OUT_PATH)


def convert_wem(input_path, output_path):
    subprocess.run([
        VGMSTREAM_EXE,  # Executable
        '-o', str(output_path),  # Output path
        str(input_path)  # Input path
    ])


def main(argv):
    # Argument validation
    err = False
    if len(argv) == 0:
        print('Missing argument')
        err = True
    elif len(argv) > 1:
        print('Too many arguments')
        err = True
    else:
        wwise_path = Path(argv[0]).absolute()
        if not wwise_path.exists():
            print('Invalid pak directory')
            err = True
    if err:
        print('extract.py <path to pak wwise directory>')
        sys.exit(2)

    cleanup()

    # Stats
    n_banks = 0
    n_streamed = 0
    n_memory = 0

    # noinspection PyUnboundLocalVariable
    # Note: identical xml soundbank meta files are also present but json files are easier to work with in py
    for json_path in list(wwise_path.glob('*.json')):  # Iterate over all json files in the directory
        dict_ = json.loads(json_path.read_bytes())
        if 'SoundBanksInfo' in dict_:  # Make sure json file is a soundbank meta
            for soundbank in dict_['SoundBanksInfo']['SoundBanks']:
                print(f'Bank: {soundbank["ShortName"]}')
                print('=' * DIV_LENGTH)

                bank_out_path = Path(os.path.join(OUT_PATH.absolute(), soundbank['ShortName']))
                create_dir(bank_out_path)
                n_banks += 1

                if 'ReferencedStreamedFiles' in soundbank:
                    for file in soundbank['ReferencedStreamedFiles']:
                        source = str(os.path.join(wwise_path, (file['Id'] + '.wem')))
                        dest = str(os.path.join(bank_out_path, file['ShortName']))

                        # ShortName might contain more subdirectories, make sure they exist
                        create_dir(dest.parent)

                        print(f'output: {file["ShortName"]}')
                        convert_wem(source, dest)
                        n_streamed += 1
                        print('-' * DIV_LENGTH)  # Divider

                if 'IncludedMemoryFiles' in soundbank:
                    os.chdir(TMP_PATH)  # Go to tmp directory for bnkextr output

                    i = 1
                    cmd = [BANK_EXTR_EXE, os.path.join(wwise_path, soundbank['Path'])]
                    print(cmd)
                    subprocess.run(cmd)  # Extract soundbank to cwd
                    for file in soundbank['IncludedMemoryFiles']:

                        # Prefetched files are actually in ReferencedStreamedFiles and should thus be skipped
                        if 'PrefetchSize' not in file:
                            source = Path(f'{i:04d}.wem')  # Filename for bnkextr output (4 digits, leading zeroes)
                            dest = str(os.path.join(bank_out_path, file['ShortName']))

                            # ShortName might contain more subdirectories, make sure they exist
                            create_dir(dest.parent)

                            print(f'output: {file["ShortName"]}')
                            convert_wem(source, dest)
                            n_memory += 1
                            print('-' * DIV_LENGTH)  # Divider
                        i += 1

                    os.chdir(MODULE_PATH)

                print('=' * DIV_LENGTH)  # Divider

        else:
            print(f'Non SoundBankInfo json file skipped: {json_path}')

    print(f'Done. Converted {n_memory + n_streamed} files ({n_streamed} disk, {n_memory} mem) from {n_banks} banks.')


if __name__ == '__main__':
    main(sys.argv[1:])

```

**Comment by florensie** [comment]
Using `/` for concatenation should work just fine with pathlib. Also, I don't recall there being any recursion in this script?

**Comment by Pomax** [comment]
wrong word - it iterates into a dir from what I can tell, but then fails at that:
```
> python extract.py "f:\Steam\steamapps\common\Yokus Island Express\data\sounds\windows"
Non SoundBankInfo json file skipped: f:\Steam\steamapps\common\Yokus Island Express\data\sounds\windows\PluginInfo.json
Bank: backgrounds
==================================================
['c:\\Users\\Mike\\Downloads\\extract\\bnkextr.exe', 'f:\\Steam\\steamapps\\common\\Yokus Island Express\\data\\sounds\\windows\\backgrounds.bnk']
Divinity 2: Ego Draconis / Army of Two .BNK extractor
(c) CTPAX-X Team 2009-2010
http://www.CTPAX-X.ru/

.001.wav
.002.wav
.003.wav
.004.wav
.005.wav
.006.wav
.007.wav
.008.wav
.009.wav
.010.wav
.011.wav
.012.wav
.013.wav
.014.wav
.015.wav
.016.wav
.017.wav
.018.wav
.019.wav
.020.wav
.021.wav
.022.wav
.023.wav
Traceback (most recent call last):
  File "extract.py", line 133, in <module>
    main(sys.argv[1:])
  File "extract.py", line 114, in main
    create_dir(dest.parent)
AttributeError: 'str' object has no attribute 'parent'
```

**Comment by florensie** [comment]
Hmm, I'll take a better look at it later.

**Comment by florensie** [comment]
I looked into it a bit closer again. It seems like pathlib is broken or doesn't have the features I use on python version below 3.8.

**Comment by Pomax** [comment]
Ah, I see. In that case: time to upgrade!

Also, it might be nice to check `sys.version` and have it exit with something like `This script requires Python 3.8 or above` or something similar =)

**Comment by florensie** [comment]
Yeah I already checked for version 3.6 before so I changed it to be 3.8. Just haven't put a message yet.
